---
# handlers file for roles/kubernetes
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kubelet service
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true

- name: Restart haproxy service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
