- name: "Kubernetes: -- Get administrative master node --"
  ansible.builtin.import_tasks:
    file: enviroment/get-master.yml

- name: "Kubernetes: -- Install Calico CNI plugin --"
  become: true
  run_once: true
  delegate_to: "{{ administrative_master_node }}"
  block:
    - name: "Kubernetes: -- Create temp calico directory --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/calico"
        state: directory
        mode: "0755"

    - name: "Kubernetes: -- Copy calico operator manifests --"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ kubernetes_tmp_configs_dir }}/calico/{{ item.path | basename |
          regex_replace('\\.j2$', '') }}"
        mode: "0644"
      with_filetree: "{{ role_path }}/templates/manifests/cni/calico/{{
        kubernetes_calico_chart_version }}/manifests/"
      when: item.state == 'file'
      loop_control:
        label: "{{ item.path | basename }}"

    - name: "Kubernetes: -- Find operator manifest files --"
      ansible.builtin.find:
        paths: "{{ kubernetes_tmp_configs_dir }}/calico"
        patterns: [ "*.yaml", "*.yml" ]
        excludes: [ "init-calico.yml" ]
      register: calico_operator_files

    - name: "Kubernetes: -- Install calico operator --"
      kubernetes.core.k8s:
        src: "{{ item.path }}"
        state: present
        apply: yes
        server_side_apply:
          field_manager: ansible
          force_conflicts: true
      register: result
      until: result is succeeded
      retries: 5
      delay: 20
      loop: "{{ calico_operator_files.files | sort(attribute='path') }}"
      loop_control:
        label: "{{ item.path | basename }}"

    - name: "Kubernetes: -- Wait for Installation CRD --"
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: installations.operator.tigera.io
      register: crd_result
      until: crd_result.resources | length > 0
      retries: 30
      delay: 10

    - name: "Kubernetes: -- Copy init-calico manifest --"
      ansible.builtin.template:
        src: "manifests/cni/calico/init-calico.yml.j2"
        dest: "{{ kubernetes_tmp_configs_dir }}/calico/init-calico.yml"
        mode: "0644"

    - name: "Kubernetes: -- Apply init-calico --"
      kubernetes.core.k8s:
        src: "{{ kubernetes_tmp_configs_dir }}/calico/init-calico.yml"
        state: present
        apply: yes
        server_side_apply:
          field_manager: ansible
          force_conflicts: true

    - name: "Kubernetes: -- Remove calico temp directory --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/calico"
        state: absent
