- name: "Kubernetes: -- Get administrative master node --"
  ansible.builtin.import_tasks:
    file: enviroment/get-master.yml

- name: "Kubernetes: -- Install Calico CNI plugin --"
  become: true
  run_once: true
  delegate_to: "{{ administrative_master_node }}"
  block:
    - name: "Kubernetes: -- Create temp calico directory --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/calico"
        state: directory
        mode: "0755"

    - name: "Kubernetes: -- Copy calico operator manifests --"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ kubernetes_tmp_configs_dir }}/calico/{{ item.path | basename |
          regex_replace('\\.j2$', '') }}"
        mode: "0644"
      with_filetree: "{{ role_path }}/templates/manifests/cni/calico/{{
        kubernetes_calico_chart_version }}/manifests/"
      when: item.state == 'file'
      loop_control:
        label: "{{ item.path | basename }}"

    - name: "Kubernetes: -- Copy init-calico manifest --"
      ansible.builtin.template:
        src: "manifests/cni/calico/init-calico.yml.j2"
        dest: "{{ kubernetes_tmp_configs_dir }}/calico/init-calico.yml"
        mode: "0644"

    - name: "Kubernetes: -- Find calico manifest files --"
      ansible.builtin.find:
        paths: "{{ kubernetes_tmp_configs_dir }}/calico"
        patterns: [ "*.yaml", "*.yml" ]
      register: calico_manifest_files

    # BUG: calico-typha/calico-apiserver не устанавливаются под и нод аффинити
    # BUG: надо перепроверить что apply проходит нормально
    - name: "Kubernetes: -- Install cni plugin --"
      kubernetes.core.k8s:
        src: "{{ item.path }}"
        state: present
      register: result
      until: result is succeeded
      retries: 5
      delay: 20
      loop: "{{ calico_manifest_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
    - name: "Kubernetes: -- Remove calico temp directory --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/calico"
        state: absent
