- name: "Kubernetes: -- Get administrative master node --"
  ansible.builtin.import_tasks:
    file: enviroment/get-master.yml

- name: "Kubernetes: -- Install ingress controller nginx --"
  become: true
  run_once: true
  delegate_to: "{{ administrative_master_node }}"
  block:
    - name: "Kubernetes: -- Copy ingress controller nginx manifest --"
      ansible.builtin.template:
        src: "manifests/ingress/ingress-nginx.yml.j2"
        dest: "{{ kubernetes_tmp_configs_dir }}/ingress-nginx.yml"
        mode: "0644"
    - name: "Kubernetes: -- Install ingress controller nginx --"
      ansible.builtin.k8s:
        src: "{{ kubernetes_tmp_configs_dir }}/ingress-nginx.yml"
        state: present
    - name: "Kubernetes: -- Remove ingress controller nginx manifest --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/ingress-nginx.yml"
        state: absent
