---
- name: "Kubernetes: -- Get administrative master node --"
  ansible.builtin.import_tasks:
    file: enviroment/get-master.yml

- name: Get Kubernetes nodes
  kubernetes.core.k8s_info:
    kind: Node
  register: kube_nodes
  changed_when: false
  delegate_to: "{{ administrative_master_node }}"
  run_once: true

- name: Set fact for Kubernetes nodes
  set_fact:
    kube_nodes_list: "{{ kube_nodes.resources | map(attribute='metadata.name') | list }}"

- name: Find hosts not in Kubernetes cluster
  set_fact:
    hosts_not_in_kube: "{{ groups[kubernetes_master_group_name] | difference(kube_nodes_list) }}"

- name: Debug hosts_not_in_kube
  debug:
    var: hosts_not_in_kube

# - name: Apply tasks only on hosts not in Kubernetes cluster
#   block:
#     - name: Example task
#       debug:
#         msg: "This host is not in the Kubernetes cluster"
#   when: inventory_hostname in hosts_not_in_kube