- name: "Kubernetes: -- Get administrative master node --"
  ansible.builtin.import_tasks:
    file: enviroment/get-master.yml

- name: "Kubernetes: -- Install node local dns --"
  become: true
  run_once: true
  delegate_to: "{{ administrative_master_node }}"
  block:
    - name: "Kubernetes: -- Get information about kube-dns service --"
      kubernetes.core.k8s_info:
        kind: Service
        name: kube-dns
        namespace: kube-system
        field_selectors:
          - spec.clusterIP
      register: kube_dns_service_info
    - name: Extract ClusterIP using Jinja2 filter
      ansible.builtin.set_fact:
        kubernetes_kube_dns_service_ip: "{{ kube_dns_service_info.resources[0].spec.clusterIP }}"
    - name: "Kubernetes: -- Copy node local dns manifest --"
      ansible.builtin.template:
        src: "manifests/dns/nodelocaldns.yml.j2"
        dest: "{{ kubernetes_tmp_configs_dir }}/nodelocaldns.yml"
        mode: "0644"
    - name: "Kubernetes: -- Install node local dns --"
      kubernetes.core.k8s:
        src: "{{ kubernetes_tmp_configs_dir }}/nodelocaldns.yml"
        state: present
    - name: "Kubernetes: -- Remove node local dns manifest --"
      ansible.builtin.file:
        path: "{{ kubernetes_tmp_configs_dir }}/nodelocaldns.yml"
        state: absent
